name: Notify Zulip Action
description: Send Github Actions workflow status notifications to Zulip
author: Aman Agrawal 
inputs:
  status:
    description: Job Status
    required: true
  notify_when:
    description: Specify on which events a zulip notification is sent
    required: false
    default: 'success,failure,warnings'

branding:
  icon: send
  color: blue

runs:
  using: docker
  image: Dockerfile
